import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import UIProvider from '@/providers/NextUIProvider'
import { ListOfWordsProvider } from '@/hooks/listOfWords'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className="">
      <body className={inter.className}>
        <UIProvider>
          <ListOfWordsProvider>{children}</ListOfWordsProvider>
        </UIProvider>
      </body>
    </html>
  )
}
